### ISSUE TITLE
Add Arabic Translation

### ISSUE THREAD

**Issue by abdulmuizz0903** [Bartozo/Life-Progress-Android#11]
Add Arabic translation for Arab speaking users.

**Comment by Bartozo** [comment]
👋 Hey, If you want to contribute to the project and know the Arabic language then feel free to make a pull request for that. I think the text in that language should be displayed from right to left, but as far as I know this is supported out of the box in jetpack compose. So adding only language should be fine.

If you need any help feel free to message me here or find me on Twitter 😊

**Comment by abdulmuizz0903** [comment]
I have made the pull request. You can merge it with the main branch.

**Comment by Bartozo** [comment]
Thank you for making the pull request for that 🙏 I will check it on Monday and if everything will be fine, then I will also make a new release with your translations on that day 🙌

**Comment by abdulmuizz0903** [comment]
Thanks a lot

**Comment by Bartozo** [comment]
Just checked your pull request 😀

**Comment by Bartozo** [comment]
Your pull request has been just merged to main branch. I will close this issue now.

Thank you for your contribution 🙏
